# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  ğŸ‰ Thanks for opening your first issue here! Be sure to follow the issue template! âœ”
  We will notify you as soon as possible ğŸ‘©â€ğŸ’»
  You just need to wait a time while and check your email ğŸ’Œ
  
# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  ğŸ‰ Thanks for opening this pull request! Please check out our contributing guidelines. âœ”
  We will notify you as soon as possible ğŸ‘©â€ğŸ’»
  You just need to wait a time while and check your email ğŸ’Œ
  
# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  ğŸ‰ Congrats on merging your first pull request! We here at behaviorbot are proud of you! âœ”
  We will notify you as soon as possible ğŸ‘©â€ğŸ’»
  You just need to wait a time while and check your email ğŸ’Œ
